return {
  window = {
    window_left = "<C-h>",
    window_lower = "<C-j>",
    window_upper = "<C-k>",
    window_right = "<C-l>",
  },
  resize_window = {
    size_increase_height = "<C-Up>",
    size_decrease_height = "<C-Down>",
    size_decrease_width = "<C-Left>",
    size_increase_width = "<C-Right>",
  },
  move_lines = {
    move_down = "<A-j>",
    move_up = "<A-k>",
  },
  buffers = {
    buf_prev = "<S-h>",
    buf_next = "<S-l>",
    buf_prev_alt = "[b",
    buf_next_alt = "]b",
    buf_switch_to_other = "<leader>bb",
    buf_switch_to_other_alt = "<leader>`",
    buf_delete = "<leader>bX",
    buf_delete_and_close = "<leader>bD",
  },
  clear_search_diff_update_and_redraw = "<leader>ur",
  save_file = "<C-s>",
  keywordprg = "",
  commenting = {
    comment_add_below = "gco",
    comment_add_above = "gcO",
  },
  lazy = "<leader>pp",
  new_file = "<leader>n",
  location_list = "<leader>xl",
  quickfix_list = "<leader>xq",
  previous_quickfix = "[q",
  next_quickfix = "]q",
  format = "<leader>lf",
  diagnostics = {
    diagnostic_line_diagnostics = "<leader>ld",
    diagnostic_next_diagnostic = "]d",
    diagnostic_prev_diagnostic = "[d",
    diagnostic_next_error = "]e",
    diagnostic_prev_error = "[e",
    diagnostic_next_warning = "]w",
    diagnostic_prev_warning = "[w",
  },
  toggle_options = {
    toggle_auto_format_buffer = "<leader>Sf",
    toggle_auto_format_global = "<leader>SF",
    toggle_spelling = "<leader>Ss",
    toggle_wrap = "<leader>Sw",
    toggle_relativenumber = "",
    toggle_diagnostics = "<leader>Sd",
    toggle_number = "",
    toggle_conceallevel = "",
    toggle_treesitter = "<leader>ST",
    toggle_background = "",
    toggle_inlay_hints = "<leader>SH",
  },
  lazygit = {
    lazygit_toggle_root = "",
    lazygit_toggle_cwd = "<leader>gg",
    lazygit_blame_line = "",
    lazygit_browse = "<leader>gB",
    lazygit_current_file_history = "<leader>gf",
    lazygit_git_log_root = "",
    lazygit_git_log_cwd = "<leader>gl",
  },
  quit_all = "<leader>qq",
  inspect_pos = "<leader>ui",
  inspect_tree = "<leader>uI",
  lazyvim_changelog = "",
  terminal = {
    floating_terminal = {
      terminal_toggle_root = "",
      terminal_toggle_cwd = "<leader>ot",
      terminal_toggle_root_alt_1 = "",
      terminal_toggle_root_alt_2 = "<c-_>",
    },
    terminal_enter_normal_mode = "fj",
    terminal_hide_terminal = "",
    terminal_hide_terminal_alt = "<c-_>",
  },
  windows = {
    window_prefix = "",
    window_split_window_below = "",
    window_split_window_right = "",
    window_delete_window = "",
    window_toggle_maximize_window = "",
  },
  tabs = {
    tab_last_tab = "<leader><tab>l",
    tab_close_other_tabs = "<leader><tab>o",
    tab_first_tab = "<leader><tab>f",
    tab_new_tab = "<leader><tab><tab>",
    tab_next_tab = "<leader><tab>]",
    tab_close_tab = "<leader><tab>d",
    tab_previous_tab = "<leader><tab>[",
  },
}
