return {
  nvim_notify = {
    nvimnotify_dismiss_all_notifications = "<leader>Sn",
  },
  bufferline = {
    bufferline_toggle_pin = "<leader>bp",
    bufferline_delete_non_pinned_buffers = "<leader>bP",
    bufferline_delete_other_buffers = "<leader>bo",
    bufferline_delete_buffers_to_the_right = "<leader>br",
    bufferline_delete_buffers_to_the_left = "<leader>bl",
    bufferline_prev_buffer = "<S-h>",
    bufferline_next_buffer = "<S-l>",
    bufferline_prev_buffer_alt = "[b",
    bufferline_next_buffer_alt = "]b",
    bufferline_move_buffer_prev = "[B",
    bufferline_move_buffer_next = "]B",
  },
  indent_blankline = {
    indentblankline_toggle = "<leader>ug",
  },
  noice = {
    noice_prefix = "<leader>oN",
    noice_redirect_cmdline = "<S-Enter>",
    noice_last_message = "<leader>oNl",
    noice_history = "<leader>oNh",
    noice_all = "<leader>oNa",
    noice_dismiss = "<leader>oNd",
    noice_pick = "<leader>oNt",
    noice_scroll_forward = "<c-f>",
    noice_scroll_backward = "<c-b>",
  },
  dashboard = {
    dashboard_find_file = "f",
    dashboard_new_file = "n",
    dashboard_recent_files = "r",
    dashboard_find_text = "g",
    dashboard_config = "c",
    dashboard_restore_session = "s",
    dashboard_lazy_extras = "x",
    dashboard_lazy = "l",
    dashboard_quit = "q",
    dashboard_projects = "p",
  },
}
