local map = vim.keymap.set

map({ "n" }, "<leader>tr", function()
  require("neotest").run.run()
end, { desc = "Run current test" })
map({ "n" }, "<leader>tf", function()
  require("neotest").run.run(vim.fn.expand("%"))
end, { desc = "Run tests in file" })
map({ "n" }, "<leader>tF", function()
  require("neotest").run.run(vim.uv.cwd())
end, { desc = "Run tests in path" })
map({ "n" }, "<leader>tl", function()
  require("neotest").run.run_last()
end, { desc = "Run last test" })
map({ "n" }, "<leader>ts", function()
  require("neotest").summary.toggle()
end, { desc = "Summary" })
map({ "n" }, "<leader>to", function()
  require("neotest").output_panel.toggle()
end, { desc = "Toggle output panel" })
map({ "n" }, "<leader>tO", function()
  require("neotest").output.open({ enter = true, auto_close = true })
end, { desc = "Show output" })
map({ "n" }, "<leader>tS", function()
  require("neotest").run.stop()
end, { desc = "Stop" })
map({ "n" }, "<leader>tw", function()
  require("neotest").watch.toggle(vim.fn.expand("%"))
end, { desc = "Toggle watch" })
map({ "n" }, "<leader>tu", function()
  require("neotest").summary.toggle()
  require("neotest").output_panel.toggle()
end, { desc = "Toggle UI" })
